// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
export { renderDocument, renderToStream, renderToString, toView } from "obix-core-ssr";
export type { RenderOptions, RenderView, ServerDocument } from "obix-core-ssr";
